[package]
name = "lazy-atomic"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.1"
flume = "0.10.14"
libc = "0.2.133"
once_cell = "1.15.0"
cfg-if = "1.0.0"

[dev-dependencies]
crossbeam = "0.8.2"
